### ISSUE TITLE
Kubernetes deployment advice

### ISSUE THREAD

**Issue by BRUHItsABunny** [storj/drpc#27]
Hey, I was wondering what the best way of deploying this as an exposed service to kubernetes would be.

I made a yaml file containing a deployment and a service exposing port 9001 and 1 replica.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: censored 
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
```

I also made an Ingress that selects my Service from above, note I added the annotation ``nginx.ingress.kubernetes.io/backend-protocol: "GRPC"``

```
kind: Ingress
metadata:
  name: api-grpc-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  ingressClassName: nginx
  rules:
    - host: "api.domain.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 9001
```

After this I pointed a subdomain to the IP of the node that has the Ingress pod running on it, when I run a port scan on api.domain.com port 9001 is open

Yet whenever I try to run a client locally to contact that exposed service (api.domain.com:9001), no error occurs when setting up the client but every rpc fails:
```
    server_test.go:366: context canceled
    server_test.go:371: manager closed: EOF
    server_test.go:377: manager closed: EOF
    server_test.go:377: manager closed: EOF
    server_test.go:366: manager closed: EOF
    server_test.go:371: manager closed: EOF
    server_test.go:377: manager closed: EOF
    server_test.go:377: manager closed: EOF
    ...
```

Does anyone know how to get this to work?
